<? include("../../include.php");
echo drawTop('<a href="/fyi/">For Your Information</a> - Accessing Food Stamps');?>
<div class="panel">You can <a href="food-stamps.pdf">download</a> this tip sheet and take it with you.</div>

<i>Written in Collaboration with Johannah Westmacott</i>

<p><b>A Brief Overview of Public Benefits</b><br>
Everybody in New York City has a legal right to food, medical care, and shelter – even if they can’t pay for it. New York City government is legally required to provide these things for people who can’t afford them. The city’s solutions to providing food and healthcare to its citizens are Food Stamps (money for groceries) and Medicaid (health insurance). You can apply for these things separately by going to a Food Stamps-only office to apply for Food Stamps and a Medicaid-only office to apply for Medicaid. You can also go to a Welfare office and apply for both of these things at the same time as applying for Public Assistance (cash benefits).</p>
<p><i>We recommend applying for Food Stamps separately</i>, because while everyone is legally entitled to Food Stamps and Medicaid, no one is legally entitled to Public Assistance. When you apply at a Welfare office for all three benefits, your applications are connected. If you are denied Public Assistance, or even if you initially qualify for it but do not meet the continued requirements later on, there is a chance the city will cut off your Food Stamp and Medicaid benefits at the same time. They are not technically allowed to do this, but it still happens. It is one of the many ways the city makes it difficult for people to access public benefits.</p>

<p><b>What Are Food Stamps?</b><br>
The Food Stamp Program is designed to help people be able to buy food, by providing a monthly installment of money that can only be used to buy groceries. Food Stamps are no longer in actual stamp form – now you get an electronic benefit card that you can use to buy food at participating stores - just look for a sign that says, “We accept EBT” or ask the cashier. You receive a Personal Identification Number (PIN) so it works just like a credit or debit card. Food Stamps can be used at most grocery stores and supermarkets. They can be used at stores which sell healthy and organic foods like Trader Joes and Whole Foods. They can also be used at participating Green Markets throughout the city.</p>

<p><b>Who Qualifies?</b><br>
You don’t have to be living on the street to qualify, although if you are homeless, you automatically qualify. Eligibility rules are constantly changing. To find out if you’re eligible, fill out a Food Stamps application, <a href="http://www.otda.state.ny.us/main/apps/4826.pdf">available online</a> or just go to a Food Stamps office and talk to a worker there. Only U.S. citizens can apply, and it is possible that when you apply they will run a warrant check on your name to see if the cops in New York are looking for you. Students have to be working in order to apply, but nobody else does.</p>

<p><b>Filling out the Application</b><br>
There are Food Stamps offices in every borough of New York. Go to the one closest to where you live - otherwise they will send you away. If you are homeless you can go to any Food Stamps office and be seen by a worker. You can find an updated list of all of the city’s <a href="http://www.nyc.gov/html/hra/downloads/pdf/food_stamp_offices_0108.pdf">Food Stamps offices online</a>.  If you need help filling out the application, you just have to be sure you get your name, address (if you have one) and signature on it. Once it has that information on it they are legally required to accept it and help you fill out the rest.</p>
<p>If you do not have any identification, you are still legally entitled to Food Stamps. If you know your social security number (even if you don't have a social security card) you can request a Confirmation of Identification form from the Food Stamps workers (form W133AA). They can verify that you are who you say you are and submit your application without ID. When you get your benefit card, make sure you get one with a photo on it. This is a government-issued photo ID with your name, birth date, and signature on it. For all official purposes, it is as good as a state ID.</p>

<p><b>What to Expect</b><br>
If the city government actually provided food, shelter, and health care to everyone who could not afford it, they would have to rethink their priorities and make a new budget. They make them difficult to access in order to discourage people from applying. Try to keep this in mind if you feel that you are being dismissed by a rude welfare worker. Their attitude is probably not about you as a person, but about the fact that they are mandated to make the system inaccessible. Some government workers are actually helpful people, but if you happen to end up talking to someone who is not, try to stay calm and polite. Do not be rude in response to the government workers; however, Do not take "no" or "come back later" for an answer. You are much more likely to get what you want out of a worker if you are persistent and assertive.</p>
<p>Try to bring all necessary documentation with you to complete the application. This can include: government- issued identification, proof of income (if you are working), proof of residence (if you have one), bank statements, proof of pregnancy or children. If possible, set aside a whole morning, afternoon, or a whole day. Arrive as early as possible and be prepared to wait.</p>
<p>It can take up to a month for your Food Stamps application to be processed. When you are approved you will be reimbursed for that waiting period (your benefits will be retroactive to the date that you applied). If you can’t or don’t want to wait for the application to go through, you can ask your worker about Expedited Processing. If you have less than $100 cash or other resources and you will make less than $150 this month you can apply for Expedited Processing. You are also eligible for Expedited Processing if your income is less than your rent or mortgage plus heat, utilities, and phone costs. Migrant or seasonal farm workers can also apply for Expedited Processing.</p>

<p><b>Recertifying</b><br>
Once you are approved for Food Stamps you will have to recertify every six months. This means that you will have to prove that you are still eligible to get them. The Food Stamps office will not take heroic measures to find you and remind you to recertify. They are supposed to notify you by mail, but often times they don’t. If you don’t have a mailing address or if you move around or if you just want to make sure they don’t forget you, you should keep track of when your six months are almost up and go in yourself to recertify. Recertification can be done over the phone or in person, but you will have to mail or fax in certain required documents. If you miss your recertification deadline you can reapply and start over.</p>

<p>For more information on Food Stamps:<br>
<a href="http://www.nyc.gov/html/hra/html/directory/food.shtml">Information Online</a><br>
Human Resources Administration Infoline (the ones who give out Food Stamps): 1-877-472-8411<br>
Expedited Processing of Food Stamps Information: 1-800-342-3009<br>
Public Benefits Resource Center (Benefits counseling over the phone): 212-614-5444 or 212-614-5552</p>

<? echo drawBottom(); ?>